/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinemasystem;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class addMovies extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;


    public addMovies() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        titleTF = new javax.swing.JTextField();
        genreTF = new javax.swing.JTextField();
        timeCB = new javax.swing.JComboBox<>();
        hallCB = new javax.swing.JComboBox<>();
        backButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        dayCB = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        monthCB = new javax.swing.JComboBox<>();
        hoursCB = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        minsCB = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        ratingCB = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Movies");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add Movie Show");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Movie Title :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Movie Genre :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Movie Rating :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Day :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hall Category :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Movie Duration :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));
        getContentPane().add(titleTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 284, -1));
        getContentPane().add(genreTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 284, -1));

        timeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12:00", "15:00", "18:00", "21:00", "00:00 " }));
        getContentPane().add(timeCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 284, -1));

        hallCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silver", "Gold", "Platinum" }));
        getContentPane().add(hallCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 284, -1));

        backButton.setBackground(new java.awt.Color(204, 0, 0));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 609, 100, -1));

        addButton.setBackground(new java.awt.Color(0, 255, 0));
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 100, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 200, -1));

        dayCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(dayCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 90, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Month :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));

        monthCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        getContentPane().add(monthCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 120, -1));

        hoursCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(hoursCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 306, 90, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("hours");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 310, -1, -1));

        minsCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        minsCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minsCBActionPerformed(evt);
            }
        });
        getContentPane().add(minsCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 306, 71, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("minutes");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 310, -1, -1));

        ratingCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "2.0", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7", "2.8", "2.9", "3.0", "3.1", "3.2", "3.3", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9", "4.0", "4.1", "4.2", "4.3", "4.4", "4.5", "4.6", "4.7", "4.8", "4.9", "5.0", "5.1", "5.2", "5.3", "5.4", "5.5", "5.6", "5.7", "5.8", "5.9", "6.0", "6.1", "6.2", "6.3", "6.4", "6.5", "6.6", "6.7", "6.8", "6.9", "7.0", "7.1", "7.2", "7.3", "7.4", "7.5", "7.6", "7.7", "7.8", "7.9", "8.0", "8.1", "8.2", "8.3", "8.4", "8.5", "8.6", "8.7", "8.8", "8.9", "9.0", "9.1", "9.2", "9.3", "9.4", "9.5", "9.6", "9.7", "9.8", "9.9", "10.0" }));
        getContentPane().add(ratingCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 280, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemasystem/movies.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new adminHome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (titleTF.getText().isEmpty()||genreTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all the fields");
        }
        else {
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://Movies.accdb");
                pst = con.prepareStatement("insert into movies(title,genre,rating,duration,datee,time,hall)values(?,?,?,?,?,?,?) ");
                pst.setString(1, titleTF.getText());
                pst.setString(2, genreTF.getText());
                pst.setString(3, ratingCB.getSelectedItem().toString());
                pst.setString(4, hoursCB.getSelectedItem().toString() + " " + minsCB.getSelectedItem().toString());
                Date date = new Date(120,monthCB.getSelectedIndex(),dayCB.getSelectedIndex() + 1);
                pst.setString(5, date.toString());
                pst.setString(6, timeCB.getSelectedItem().toString());
                pst.setString(7, hallCB.getSelectedItem().toString());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Movie Show Added.");
                
                pst = con.prepareStatement("select * from movies");
                rs = pst.executeQuery();
            
                ResultSetMetaData rsd = rs.getMetaData();
           
                Object[] array = new Object[8];
                
                while(rs.next())
                {
                    array[0] = rs.getString("showID");
                    array[1] = rs.getString("title");
                    array[2] = rs.getString("genre");                   
                    array[3] = rs.getString("rating");
                    Object[] duration = rs.getString("duration").split(" ");
                    array[4] = duration[0] + " hours " + duration[1] + " mins";
                    array[5] = rs.getString("datee");
                    array[6] = rs.getString("time");
                    array[7] = rs.getString("hall");      
                }
                if(array[7].equals("Silver")) {
                    silverHall h = new silverHall(Integer.parseInt( (String) array[0]));
                }
                else if(array[7].equals("Gold")) {
                    goldHall h = new goldHall(Integer.parseInt( (String) array[0]));
                }
                else if(array[7].equals("Platinum")) {
                    platinumHall h = new platinumHall(Integer.parseInt( (String) array[0]));
                }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(addMovies.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(addMovies.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(addMovies.class.getName()).log(Level.SEVERE, null, ex);
                }

                titleTF.setText("");
                genreTF.setText("");
                ratingCB.setSelectedIndex(0);
                hoursCB.setSelectedIndex(0);
                minsCB.setSelectedIndex(0);
                dayCB.setSelectedIndex(0);
                monthCB.setSelectedIndex(0);
                timeCB.setSelectedIndex(0);
                hallCB.setSelectedIndex(0);
        }    
            
 
    }//GEN-LAST:event_addButtonActionPerformed

    private void minsCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minsCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minsCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addMovies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> dayCB;
    private javax.swing.JTextField genreTF;
    private javax.swing.JComboBox<String> hallCB;
    private javax.swing.JComboBox<String> hoursCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> minsCB;
    private javax.swing.JComboBox<String> monthCB;
    private javax.swing.JComboBox<String> ratingCB;
    private javax.swing.JComboBox<String> timeCB;
    private javax.swing.JTextField titleTF;
    // End of variables declaration//GEN-END:variables
}
