/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinemasystem;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dell
 */
public class adminHome extends javax.swing.JFrame {

    /**
     * Creates new form adminHome
     */
    public adminHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        addMoviesButton = new javax.swing.JButton();
        updateMoviesButton = new javax.swing.JButton();
        btnUpdateHalls = new javax.swing.JButton();
        btnUpdateCredentials = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 110, 10));

        addMoviesButton.setBackground(new java.awt.Color(255, 255, 255));
        addMoviesButton.setText("Add Movies");
        addMoviesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoviesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addMoviesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 140, -1));

        updateMoviesButton.setBackground(new java.awt.Color(255, 255, 255));
        updateMoviesButton.setText("Update Movies");
        updateMoviesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMoviesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateMoviesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 140, -1));

        btnUpdateHalls.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateHalls.setText("Update Halls");
        btnUpdateHalls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateHallsActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateHalls, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 140, -1));

        btnUpdateCredentials.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateCredentials.setText("Update Credentials");
        btnUpdateCredentials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCredentialsActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateCredentials, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        logoutButton.setBackground(new java.awt.Color(204, 0, 0));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemasystem/cinema.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addMoviesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoviesButtonActionPerformed
        new addMovies().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addMoviesButtonActionPerformed

    private void btnUpdateHallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateHallsActionPerformed
        try {
            new editHall().setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(adminHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateHallsActionPerformed

    private void btnUpdateCredentialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCredentialsActionPerformed
        try {
            new updateCredentials().setVisible(true);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(adminHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateCredentialsActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        new login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void updateMoviesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMoviesButtonActionPerformed
        try {
            new updateMovies().setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(adminHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(adminHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_updateMoviesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMoviesButton;
    private javax.swing.JButton btnUpdateCredentials;
    private javax.swing.JButton btnUpdateHalls;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton updateMoviesButton;
    // End of variables declaration//GEN-END:variables
}
