
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinemasystem;

import java.awt.Dimension;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Dell
 */
public class receipt extends javax.swing.JFrame {

    private boolean tempvalue[][];
    private int c;
   
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public receipt(boolean[][] array,movie m, customer cus) throws IOException {
        initComponents();
        RandomAccessFile file = new RandomAccessFile("hall.dat","rw");
        
        boolean found = false;
        while(!found && (file.getFilePointer() < file.length()) ) {
           
            if(file.readInt() == m.getId()){
                found = true;
                file.readInt();        
                
                for(int i=0;i<array.length;i++){
                    for(int j=0;j<array[0].length;j++){            
                        if(array[i][j]) {                    
                            file.writeBoolean(true);
                        }
                        else {
                            file.readBoolean();
                        }
                    }
                }
            }
            else{
                int skip = file.readInt();
                file.seek(file.getFilePointer() + skip);
            }
        }
        
        for(int i = 0; i < array.length; i++) {
            for(int j = array[0].length - 1; j >= 0; j--) {
                if(array[i][j]) {
                    c++;
                    seatsTF.addItem( (char)(i+65) + "" + (array[0].length - j) );
                }
            }
        }
        idTF.setEditable(false);
        titleTF.setEditable(false);
        hallTF.setEditable(false);
        dateTF.setEditable(false);
        timeTF.setEditable(false);
        nameTF.setEditable(false);
        numberTF.setEditable(false);
        amountTF.setEditable(false);
        
        idTF.setText(Integer.toString(m.getId()));
        titleTF.setText(m.getTitle());
        hallTF.setText(m.getHall());
        dateTF.setText(m.getDate());
        timeTF.setText(m.getTime());
        nameTF.setText(cus.getName());
        numberTF.setText(Integer.toString(c));
        amountTF.setText(Double.toString(cus.getAmount(c, m.getHall())));
        
        
        try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://customers.accdb");
                pst = con.prepareStatement("insert into customer(Namee,CNIC,Address,Phone,showID,tickets,amount)values(?,?,?,?,?,?,?) ");
                pst.setString(1, cus.getName());
                pst.setString(2, cus.getCnic());
                pst.setString(3, cus.getAddress());
                pst.setString(4, cus.getPhone());
                pst.setString(5, Integer.toString(m.getId()));
                pst.setString(6, Integer.toString(c));
                pst.setString(7, Double.toString(cus.getAmount(c, m.getHall())));
                
                pst.executeUpdate();
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(customerDetails.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(customerDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idTF = new javax.swing.JTextField();
        titleTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hallTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        timeTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        numberTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        seatsTF = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        amountTF = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnBackToMovies = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Receipt");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTFActionPerformed(evt);
            }
        });
        getContentPane().add(idTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 211, -1));

        titleTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTFActionPerformed(evt);
            }
        });
        getContentPane().add(titleTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 211, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Receipt");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 129, 10));

        jLabel2.setText("Show ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel3.setText("Movie Title:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel4.setText("Hall Category:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        getContentPane().add(hallTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 211, -1));

        jLabel5.setText("Show Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel6.setText("Show Time:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));
        getContentPane().add(dateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 211, -1));
        getContentPane().add(timeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 211, -1));

        jLabel7.setText("Customer Name:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        getContentPane().add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 211, -1));

        jLabel8.setText("Number of Tickets:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));
        getContentPane().add(numberTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 211, -1));

        jLabel9.setText("Seat Numbers:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        getContentPane().add(seatsTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 211, -1));

        jLabel10.setText("Total Amount:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        amountTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTFActionPerformed(evt);
            }
        });
        getContentPane().add(amountTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 211, -1));

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 120, -1));

        btnBackToMovies.setBackground(new java.awt.Color(255, 255, 255));
        btnBackToMovies.setText("Back to Movies");
        btnBackToMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMoviesActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackToMovies, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, -1, -1));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 440, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void titleTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTFActionPerformed

    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTFActionPerformed

    private void amountTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTFActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackToMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMoviesActionPerformed
        try {
            new viewMovies().setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(receipt.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(receipt.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnBackToMoviesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                boolean a[][] = null;
                movie m = null;
                customer c = null;
                try {
                    new receipt(a,m,c).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(receipt.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTF;
    private javax.swing.JButton btnBackToMovies;
    private javax.swing.JButton btnExit;
    private javax.swing.JTextField dateTF;
    private javax.swing.JTextField hallTF;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField numberTF;
    private javax.swing.JComboBox<String> seatsTF;
    private javax.swing.JTextField timeTF;
    private javax.swing.JTextField titleTF;
    // End of variables declaration//GEN-END:variables
}
